language: node_js
node_js:
  - 10.15.3
cache:
  directories:
    - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=d2f4bbd38356616ce481b0a81a7b65d6dd508041d232f067be3ec39d60e34910
before_script:
  - export CC_TEST_REPORTER_ID=d2f4bbd38356616ce481b0a81a7b65d6dd508041d232f067be3ec39d60e34910
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:coveralls -- -u
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
